version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: SpringTp
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3310:3306"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3309/SpringTp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - "C:/Program Files/Docker/Docker/resources/bin/docker.exe:/usr/bin/docker"
    networks:
      - default

volumes:
  jenkins_home: