version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: SpringTp
      # Permet le mot de passe root vide
      MYSQL_ALLOW_EMPTY_PASSWORD: "true" # <--- Ajouté ici
    ports:
      - "3309:3306"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3309/SpringTp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: # <--- Le mot de passe reste vide ici